compile:
	gcc -o head head.c -Wall -pedantic-errors
	gcc -o wc wc.c -Wall -pedantic-errors
	gcc -o tail tail.c -Wall -pedantic-errors
	gcc -o env env.c -Wall -pedantic-errors
	gcc -o true true.c -Wall -pedantic-errors
	gcc -o false false.c -Wall -pedantic-errors

clean:
	rm head
	rm wc
	rm tail
	rm env
	rm true
	rm false
