compile:
	g++ -o exclusive exclusive.cpp -Wall -pedantic-errors
	g++ -o primesum primesum.cpp -Wall -pedantic-errors
	g++ -o endtime endtime.cpp -Wall -pedantic-errors
clean:
	rm exclusive
	rm primesum
	rm endtime
