compile:
	g++ -c -o main.o main.cpp -Wall -pedantic-errors
	g++ -c -o Matrix.o Matrix.cpp -Wall -pedantic-errors
	g++ -o main main.o Matrix.o -Wall -pedantic-errors
run:
	./main
clean:
	rm main
	rm main.o
	rm Matrix.o
