compile:
	gcc -o firstline firstline.c -Wall -pedantic-errors
	gcc -o lastline lastline.c -Wall -pedantic-errors
	gcc -o longestline longestline.c -Wall -pedantic-errors
clean:
	rm firstline
	rm lastline
	rm longestline
